[project]
name = "password-manager"
version = "0.1.0"
description = "A secure, GUI-based password manager utilizing Fernet encryption and CustomTkinter."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.4",
    "customtkinter>=5.2.2",
]
